// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjFTv4kLPLKCwiVKQ6v_lUeX8keCV1xGU',
    appId: '1:374686735651:web:bd4ca4b37461c8b15b8096',
    messagingSenderId: '374686735651',
    projectId: 'expensetracker-62188',
    authDomain: 'expensetracker-62188.firebaseapp.com',
    storageBucket: 'expensetracker-62188.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClrciVF9hFCEe6TRQYTysBRRO6WYfK_0s',
    appId: '1:374686735651:android:9e89be7bd011d7f25b8096',
    messagingSenderId: '374686735651',
    projectId: 'expensetracker-62188',
    storageBucket: 'expensetracker-62188.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5pQimTtteXUyrBDss27FDtO4WGvzWlJ0',
    appId: '1:374686735651:ios:09d314c5b5e5b6345b8096',
    messagingSenderId: '374686735651',
    projectId: 'expensetracker-62188',
    storageBucket: 'expensetracker-62188.appspot.com',
    iosClientId: '374686735651-gc7k2e4lapq711miaiihohli6ruvitbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5pQimTtteXUyrBDss27FDtO4WGvzWlJ0',
    appId: '1:374686735651:ios:09d314c5b5e5b6345b8096',
    messagingSenderId: '374686735651',
    projectId: 'expensetracker-62188',
    storageBucket: 'expensetracker-62188.appspot.com',
    iosClientId: '374686735651-gc7k2e4lapq711miaiihohli6ruvitbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseApp',
  );
}
